name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.21' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest

    - name: Install code formatter
      run: |
        sudo apt-get -y install black

    - name: Build
      run: make build

    - name: Test
      run: go test -v -coverprofile coverage.txt -covermode atomic ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

    - name: Test formatter
      run: go build -o duct cmd/duct/main.go && echo -n class A':' pass | ./duct black -l 79
